-- 创建投资者持仓表
CREATE TABLE IF NOT EXISTS investor_positions (
    id BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '主键ID',
    InstrumentID VARCHAR(31) NOT NULL COMMENT '合约代码',
    BrokerID VARCHAR(11) NOT NULL COMMENT '经纪公司代码',
    InvestorID VARCHAR(13) NOT NULL COMMENT '投资者代码',
    PosiDirection CHAR(1) NOT NULL COMMENT '持仓多空方向',
    HedgeFlag CHAR(1) NOT NULL COMMENT '投机套保标志',
    PositionDate CHAR(1) NOT NULL COMMENT '持仓日期',
    YdPosition INT NOT NULL DEFAULT 0 COMMENT '上日持仓',
    Position INT NOT NULL DEFAULT 0 COMMENT '今日持仓',
    LongFrozen INT NOT NULL DEFAULT 0 COMMENT '多头冻结',
    ShortFrozen INT NOT NULL DEFAULT 0 COMMENT '空头冻结',
    LongFrozenAmount DECIMAL(20,4) NOT NULL DEFAULT 0.0000 COMMENT '开仓冻结金额',
    ShortFrozenAmount DECIMAL(20,4) NOT NULL DEFAULT 0.0000 COMMENT '开仓冻结金额',
    OpenVolume INT NOT NULL DEFAULT 0 COMMENT '开仓量',
    CloseVolume INT NOT NULL DEFAULT 0 COMMENT '平仓量',
    OpenAmount DECIMAL(20,4) NOT NULL DEFAULT 0.0000 COMMENT '开仓金额',
    CloseAmount DECIMAL(20,4) NOT NULL DEFAULT 0.0000 COMMENT '平仓金额',
    PositionCost DECIMAL(20,4) NOT NULL DEFAULT 0.0000 COMMENT '持仓成本',
    PreMargin DECIMAL(20,4) NOT NULL DEFAULT 0.0000 COMMENT '上次占用的保证金',
    UseMargin DECIMAL(20,4) NOT NULL DEFAULT 0.0000 COMMENT '占用的保证金',
    FrozenMargin DECIMAL(20,4) NOT NULL DEFAULT 0.0000 COMMENT '冻结的保证金',
    FrozenCash DECIMAL(20,4) NOT NULL DEFAULT 0.0000 COMMENT '冻结的资金',
    FrozenCommission DECIMAL(20,4) NOT NULL DEFAULT 0.0000 COMMENT '冻结的手续费',
    CashIn DECIMAL(20,4) NOT NULL DEFAULT 0.0000 COMMENT '资金差额',
    Commission DECIMAL(20,4) NOT NULL DEFAULT 0.0000 COMMENT '手续费',
    CloseProfit DECIMAL(20,4) NOT NULL DEFAULT 0.0000 COMMENT '平仓盈亏',
    PositionProfit DECIMAL(20,4) NOT NULL DEFAULT 0.0000 COMMENT '持仓盈亏',
    PreSettlementPrice DECIMAL(20,4) NOT NULL DEFAULT 0.0000 COMMENT '上次结算价',
    SettlementPrice DECIMAL(20,4) NOT NULL DEFAULT 0.0000 COMMENT '本次结算价',
    TradingDay VARCHAR(9) NOT NULL DEFAULT '' COMMENT '交易日',
    SettlementID INT NOT NULL DEFAULT 0 COMMENT '结算编号',
    OpenCost DECIMAL(20,4) NOT NULL DEFAULT 0.0000 COMMENT '开仓成本',
    ExchangeMargin DECIMAL(20,4) NOT NULL DEFAULT 0.0000 COMMENT '交易所保证金',
    CombPosition INT NOT NULL DEFAULT 0 COMMENT '组合成交形成的持仓',
    CombLongFrozen INT NOT NULL DEFAULT 0 COMMENT '组合多头冻结',
    CombShortFrozen INT NOT NULL DEFAULT 0 COMMENT '组合空头冻结',
    CloseProfitByDate DECIMAL(20,4) NOT NULL DEFAULT 0.0000 COMMENT '逐日盯市平仓盈亏',
    CloseProfitByTrade DECIMAL(20,4) NOT NULL DEFAULT 0.0000 COMMENT '逐笔对冲平仓盈亏',
    TodayPosition INT NOT NULL DEFAULT 0 COMMENT '今日持仓',
    MarginRateByMoney DECIMAL(20,4) NOT NULL DEFAULT 0.0000 COMMENT '保证金率',
    MarginRateByVolume DECIMAL(20,4) NOT NULL DEFAULT 0.0000 COMMENT '保证金率(按手数)',
    StrikeFrozen INT NOT NULL DEFAULT 0 COMMENT '执行冻结',
    StrikeFrozenAmount DECIMAL(20,4) NOT NULL DEFAULT 0.0000 COMMENT '执行冻结金额',
    AbandonFrozen INT NOT NULL DEFAULT 0 COMMENT '放弃执行冻结',
    ExchangeID VARCHAR(9) NOT NULL DEFAULT '' COMMENT '交易所代码',
    YdStrikeFrozen INT NOT NULL DEFAULT 0 COMMENT '执行冻结的昨仓',
    InvestUnitID VARCHAR(17) NOT NULL DEFAULT '' COMMENT '投资单元代码',
    PositionCostOffset DECIMAL(20,4) NOT NULL DEFAULT 0.0000 COMMENT '持仓成本差值',
    TasPosition DECIMAL(20,4) NOT NULL DEFAULT 0.0000 COMMENT 'TAS持仓',
    TasCost DECIMAL(20,4) NOT NULL DEFAULT 0.0000 COMMENT 'TAS成本',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    
    -- 索引
    UNIQUE KEY uk_broker_investor_instrument (BrokerID, InvestorID, InstrumentID),
    INDEX idx_broker_id (BrokerID),
    INDEX idx_investor_id (InvestorID),
    INDEX idx_instrument_id (InstrumentID),
    INDEX idx_exchange_id (ExchangeID),
    INDEX idx_trading_day (TradingDay),
    INDEX idx_position (Position),
    INDEX idx_created_at (created_at),
    INDEX idx_update_time (update_time)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='投资者持仓信息表'; 