-- 行情数据表结构
-- 基于CThostFtdcDepthMarketDataField结构创建
CREATE TABLE IF NOT EXISTS market_data (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    TradingDay CHAR(9) NOT NULL COMMENT '交易日',
    InstrumentID CHAR(31) NOT NULL COMMENT '合约代码',
    ExchangeID CHAR(9) NOT NULL COMMENT '交易所代码',
    ExchangeInstID CHAR(31) COMMENT '交易所合约代码',
    LastPrice DOUBLE COMMENT '最新价',
    PreSettlementPrice DOUBLE COMMENT '上次结算价',
    PreClosePrice DOUBLE COMMENT '昨收盘',
    PreOpenInterest DOUBLE COMMENT '昨持仓量',
    OpenPrice DOUBLE COMMENT '今开盘',
    HighestPrice DOUBLE COMMENT '最高价',
    LowestPrice DOUBLE COMMENT '最低价',
    Volume INT COMMENT '数量',
    Turnover DOUBLE COMMENT '成交金额',
    OpenInterest DOUBLE COMMENT '持仓量',
    ClosePrice DOUBLE COMMENT '今收盘',
    SettlementPrice DOUBLE COMMENT '本次结算价',
    UpperLimitPrice DOUBLE COMMENT '涨停板价',
    LowerLimitPrice DOUBLE COMMENT '跌停板价',
    PreDelta DOUBLE COMMENT '昨虚实度',
    CurrDelta DOUBLE COMMENT '今虚实度',
    UpdateTime CHAR(9) COMMENT '最后修改时间',
    UpdateMillisec INT COMMENT '最后修改毫秒',
    BidPrice1 DOUBLE COMMENT '申买价一',
    BidVolume1 INT COMMENT '申买量一',
    AskPrice1 DOUBLE COMMENT '申卖价一',
    AskVolume1 INT COMMENT '申卖量一',
    BidPrice2 DOUBLE COMMENT '申买价二',
    BidVolume2 INT COMMENT '申买量二',
    AskPrice2 DOUBLE COMMENT '申卖价二',
    AskVolume2 INT COMMENT '申卖量二',
    BidPrice3 DOUBLE COMMENT '申买价三',
    BidVolume3 INT COMMENT '申买量三',
    AskPrice3 DOUBLE COMMENT '申卖价三',
    AskVolume3 INT COMMENT '申卖量三',
    BidPrice4 DOUBLE COMMENT '申买价四',
    BidVolume4 INT COMMENT '申买量四',
    AskPrice4 DOUBLE COMMENT '申卖价四',
    AskVolume4 INT COMMENT '申卖量四',
    BidPrice5 DOUBLE COMMENT '申买价五',
    BidVolume5 INT COMMENT '申买量五',
    AskPrice5 DOUBLE COMMENT '申卖价五',
    AskVolume5 INT COMMENT '申卖量五',
    AveragePrice DOUBLE COMMENT '当日均价',
    ActionDay CHAR(9) COMMENT '业务日期',
    RecordTime TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '入库时间',
    
    INDEX idx_instrument_time (InstrumentID, TradingDay, UpdateTime),
    INDEX idx_trading_day (TradingDay),
    INDEX idx_update_time (UpdateTime),
    INDEX idx_record_time (RecordTime)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='行情数据表'; 