-- 资金账户数据表结构
-- 基于CThostFtdcTradingAccountField结构创建
CREATE TABLE IF NOT EXISTS trading_account (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    BrokerID CHAR(11) NOT NULL COMMENT '经纪公司代码',
    AccountID CHAR(13) NOT NULL COMMENT '投资者帐号',
    PreMortgage DOUBLE COMMENT '上次质押金额',
    PreCredit DOUBLE COMMENT '上次信用额度',
    PreDeposit DOUBLE COMMENT '上次存款额',
    PreBalance DOUBLE COMMENT '上次结算准备金',
    PreMargin DOUBLE COMMENT '上次占用的保证金',
    InterestBase DOUBLE COMMENT '利息基数',
    Interest DOUBLE COMMENT '利息收入',
    Deposit DOUBLE COMMENT '入金金额',
    Withdraw DOUBLE COMMENT '出金金额',
    FrozenMargin DOUBLE COMMENT '冻结的保证金',
    FrozenCash DOUBLE COMMENT '冻结的资金',
    FrozenCommission DOUBLE COMMENT '冻结的手续费',
    CurrMargin DOUBLE COMMENT '当前保证金总额',
    CashIn DOUBLE COMMENT '资金差额',
    Commission DOUBLE COMMENT '手续费',
    CloseProfit DOUBLE COMMENT '平仓盈亏',
    PositionProfit DOUBLE COMMENT '持仓盈亏',
    Balance DOUBLE COMMENT '期货结算准备金',
    Available DOUBLE COMMENT '可用资金',
    WithdrawQuota DOUBLE COMMENT '可取资金',
    Reserve DOUBLE COMMENT '基本准备金',
    TradingDay CHAR(9) NOT NULL COMMENT '交易日',
    SettlementID INT COMMENT '结算编号',
    Credit DOUBLE COMMENT '信用额度',
    Mortgage DOUBLE COMMENT '质押金额',
    ExchangeMargin DOUBLE COMMENT '交易所保证金',
    DeliveryMargin DOUBLE COMMENT '投资者交割保证金',
    ExchangeDeliveryMargin DOUBLE COMMENT '交易所交割保证金',
    ReserveBalance DOUBLE COMMENT '保底期货结算准备金',
    CurrencyID CHAR(4) COMMENT '币种代码',
    PreFundMortgageIn DOUBLE COMMENT '上次货币质入金额',
    PreFundMortgageOut DOUBLE COMMENT '上次货币质出金额',
    FundMortgageIn DOUBLE COMMENT '货币质入金额',
    FundMortgageOut DOUBLE COMMENT '货币质出金额',
    FundMortgageAvailable DOUBLE COMMENT '货币质押余额',
    MortgageableFund DOUBLE COMMENT '可质押货币金额',
    SpecProductMargin DOUBLE COMMENT '特殊产品占用保证金',
    SpecProductFrozenMargin DOUBLE COMMENT '特殊产品冻结保证金',
    SpecProductCommission DOUBLE COMMENT '特殊产品手续费',
    SpecProductFrozenCommission DOUBLE COMMENT '特殊产品冻结手续费',
    SpecProductPositionProfit DOUBLE COMMENT '特殊产品持仓盈亏',
    SpecProductCloseProfit DOUBLE COMMENT '特殊产品平仓盈亏',
    SpecProductPositionProfitByAlg DOUBLE COMMENT '根据持仓盈亏算法计算的特殊产品持仓盈亏',
    SpecProductExchangeMargin DOUBLE COMMENT '特殊产品交易所保证金',
    BizType CHAR(1) COMMENT '业务类型',
    FrozenSwap DOUBLE COMMENT '延时换汇冻结金额',
    RemainSwap DOUBLE COMMENT '剩余换汇额度',
    RecordTime TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '入库时间',
    
    INDEX idx_broker_account (BrokerID, AccountID),
    INDEX idx_trading_day (TradingDay),
    INDEX idx_record_time (RecordTime),
    UNIQUE KEY uk_broker_account_trading_day (BrokerID, AccountID, TradingDay)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='资金账户数据表'; 