-- 创建投资者持仓表
CREATE TABLE IF NOT EXISTS investor_positions (
    id BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '主键ID',
    InstrumentID VARCHAR(31) NOT NULL COMMENT '合约代码',
    BrokerID VARCHAR(11) NOT NULL COMMENT '经纪公司代码',
    InvestorID VARCHAR(13) NOT NULL COMMENT '投资者代码',
    PosiDirection CHAR(1) NOT NULL COMMENT '持仓多空方向',
    HedgeFlag CHAR(1) NOT NULL COMMENT '投机套保标志',
    PositionDate CHAR(1) NOT NULL COMMENT '持仓日期',
    YdPosition INT NOT NULL DEFAULT 0 COMMENT '上日持仓',
    Position INT NOT NULL DEFAULT 0 COMMENT '今日持仓',
    LongFrozen INT NOT NULL DEFAULT 0 COMMENT '多头冻结',
    ShortFrozen INT NOT NULL DEFAULT 0 COMMENT '空头冻结',
    LongFrozenAmount DOUBLE NOT NULL DEFAULT 0.0 COMMENT '开仓冻结金额',
    ShortFrozenAmount DOUBLE NOT NULL DEFAULT 0.0 COMMENT '开仓冻结金额',
    OpenVolume INT NOT NULL DEFAULT 0 COMMENT '开仓量',
    CloseVolume INT NOT NULL DEFAULT 0 COMMENT '平仓量',
    OpenAmount DOUBLE NOT NULL DEFAULT 0.0 COMMENT '开仓金额',
    CloseAmount DOUBLE NOT NULL DEFAULT 0.0 COMMENT '平仓金额',
    PositionCost DOUBLE NOT NULL DEFAULT 0.0 COMMENT '持仓成本',
    PreMargin DOUBLE NOT NULL DEFAULT 0.0 COMMENT '上次占用的保证金',
    UseMargin DOUBLE NOT NULL DEFAULT 0.0 COMMENT '占用的保证金',
    FrozenMargin DOUBLE NOT NULL DEFAULT 0.0 COMMENT '冻结的保证金',
    FrozenCash DOUBLE NOT NULL DEFAULT 0.0 COMMENT '冻结的资金',
    FrozenCommission DOUBLE NOT NULL DEFAULT 0.0 COMMENT '冻结的手续费',
    CashIn DOUBLE NOT NULL DEFAULT 0.0 COMMENT '资金差额',
    Commission DOUBLE NOT NULL DEFAULT 0.0 COMMENT '手续费',
    CloseProfit DOUBLE NOT NULL DEFAULT 0.0 COMMENT '平仓盈亏',
    PositionProfit DOUBLE NOT NULL DEFAULT 0.0 COMMENT '持仓盈亏',
    PreSettlementPrice DOUBLE NOT NULL DEFAULT 0.0 COMMENT '上次结算价',
    SettlementPrice DOUBLE NOT NULL DEFAULT 0.0 COMMENT '本次结算价',
    TradingDay VARCHAR(9) NOT NULL COMMENT '交易日',
    SettlementID INT NOT NULL DEFAULT 0 COMMENT '结算编号',
    OpenCost DOUBLE NOT NULL DEFAULT 0.0 COMMENT '开仓成本',
    ExchangeMargin DOUBLE NOT NULL DEFAULT 0.0 COMMENT '交易所保证金',
    CombPosition INT NOT NULL DEFAULT 0 COMMENT '组合成交形成的持仓',
    CombLongFrozen INT NOT NULL DEFAULT 0 COMMENT '组合多头冻结',
    CombShortFrozen INT NOT NULL DEFAULT 0 COMMENT '组合空头冻结',
    CloseProfitByDate DOUBLE NOT NULL DEFAULT 0.0 COMMENT '逐日盯市平仓盈亏',
    CloseProfitByTrade DOUBLE NOT NULL DEFAULT 0.0 COMMENT '逐笔对冲平仓盈亏',
    TodayPosition INT NOT NULL DEFAULT 0 COMMENT '今日持仓',
    MarginRateByMoney DOUBLE NOT NULL DEFAULT 0.0 COMMENT '保证金率',
    MarginRateByVolume DOUBLE NOT NULL DEFAULT 0.0 COMMENT '保证金率(按手数)',
    StrikeFrozen INT NOT NULL DEFAULT 0 COMMENT '执行冻结',
    StrikeFrozenAmount DOUBLE NOT NULL DEFAULT 0.0 COMMENT '执行冻结金额',
    AbandonFrozen INT NOT NULL DEFAULT 0 COMMENT '放弃执行冻结',
    ExchangeID VARCHAR(9) NOT NULL COMMENT '交易所代码',
    YdStrikeFrozen INT NOT NULL DEFAULT 0 COMMENT '执行冻结的昨仓',
    InvestUnitID VARCHAR(17) NOT NULL DEFAULT '' COMMENT '投资单元代码',
    PositionCostOffset DOUBLE NOT NULL DEFAULT 0.0 COMMENT '持仓成本差值',
    TasPosition DOUBLE NOT NULL DEFAULT 0.0 COMMENT 'TAS持仓',
    TasCost DOUBLE NOT NULL DEFAULT 0.0 COMMENT 'TAS成本',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    
    -- 索引
    UNIQUE KEY uk_broker_investor_instrument (BrokerID, InvestorID, InstrumentID),
    INDEX idx_broker_id (BrokerID),
    INDEX idx_investor_id (InvestorID),
    INDEX idx_instrument_id (InstrumentID),
    INDEX idx_exchange_id (ExchangeID),
    INDEX idx_trading_day (TradingDay),
    INDEX idx_position (Position),
    INDEX idx_created_at (created_at),
    INDEX idx_update_time (update_time)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='投资者持仓信息表';

-- 插入示例数据（可选）
-- INSERT INTO investor_positions (
--     BrokerID, InvestorID, InstrumentID, HedgeFlag, PosiDirection, PositionDate,
--     YdPosition, Position, LongFrozen, ShortFrozen, LongFrozenAmount, ShortFrozenAmount,
--     OpenVolume, CloseVolume, OpenAmount, CloseAmount, PositionCost, PreMargin, UseMargin,
--     FrozenMargin, FrozenCash, FrozenCommission, CashIn, Commission, CloseProfit, PositionProfit,
--     PreSettlementPrice, SettlementPrice, TradingDay, SettlementID, OpenCost, ExchangeMargin,
--     CombPosition, CombLongFrozen, CombShortFrozen, CloseProfitByDate, CloseProfitByTrade,
--     TodayPosition, MarginRateByMoney, MarginRateByVolume, StrikeFrozen, StrikeFrozenAmount,
--     AbandonFrozen, ExchangeID, YdStrikeFrozen, InvestUnitID, PositionCostOffset
-- ) VALUES (
--     '9999', '123456', 'IF2508', '1', '2', '1',
--     0, 2, 0, 0, 0.0, 0.0,
--     2, 0, 1200000.0, 0.0, 600000.0, 120000.0, 120000.0,
--     0.0, 0.0, 0.0, 0.0, 120.0, 0.0, -5000.0,
--     3000.0, 2990.0, '20241201', 1, 600000.0, 120000.0,
--     0, 0, 0, 0.0, 0.0,
--     2, 0.1, 0.0, 0, 0.0,
--     0, 'CFFEX', 0, '', 0.0
-- ); 