-- 创建市场行情数据表
CREATE TABLE IF NOT EXISTS market_data (
    id BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '主键ID',
    TradingDay VARCHAR(9) NOT NULL COMMENT '交易日',
    InstrumentID VARCHAR(31) NOT NULL COMMENT '合约代码',
    ExchangeID VARCHAR(9) NOT NULL COMMENT '交易所代码',
    ExchangeInstID VARCHAR(31) NOT NULL COMMENT '合约在交易所的代码',
    LastPrice DOUBLE NOT NULL DEFAULT 0.0 COMMENT '最新价',
    PreSettlementPrice DOUBLE NOT NULL DEFAULT 0.0 COMMENT '上次结算价',
    PreClosePrice DOUBLE NOT NULL DEFAULT 0.0 COMMENT '昨收盘价',
    PreOpenInterest DOUBLE NOT NULL DEFAULT 0.0 COMMENT '昨持仓量',
    OpenPrice DOUBLE NOT NULL DEFAULT 0.0 COMMENT '今开盘价',
    HighestPrice DOUBLE NOT NULL DEFAULT 0.0 COMMENT '最高价',
    LowestPrice DOUBLE NOT NULL DEFAULT 0.0 COMMENT '最低价',
    Volume INT NOT NULL DEFAULT 0 COMMENT '成交量',
    Turnover DOUBLE NOT NULL DEFAULT 0.0 COMMENT '成交金额',
    OpenInterest DOUBLE NOT NULL DEFAULT 0.0 COMMENT '持仓量',
    ClosePrice DOUBLE NOT NULL DEFAULT 0.0 COMMENT '今收盘价',
    SettlementPrice DOUBLE NOT NULL DEFAULT 0.0 COMMENT '本次结算价',
    UpperLimitPrice DOUBLE NOT NULL DEFAULT 0.0 COMMENT '涨停板价',
    LowerLimitPrice DOUBLE NOT NULL DEFAULT 0.0 COMMENT '跌停板价',
    PreDelta DOUBLE NOT NULL DEFAULT 0.0 COMMENT '昨虚实度',
    CurrDelta DOUBLE NOT NULL DEFAULT 0.0 COMMENT '今虚实度',
    UpdateTime VARCHAR(9) NOT NULL COMMENT '最后修改时间',
    UpdateMillisec INT NOT NULL DEFAULT 0 COMMENT '最后修改毫秒',
    BidPrice1 DOUBLE NOT NULL DEFAULT 0.0 COMMENT '申买价一',
    BidVolume1 INT NOT NULL DEFAULT 0 COMMENT '申买量一',
    AskPrice1 DOUBLE NOT NULL DEFAULT 0.0 COMMENT '申卖价一',
    AskVolume1 INT NOT NULL DEFAULT 0 COMMENT '申卖量一',
    BidPrice2 DOUBLE NOT NULL DEFAULT 0.0 COMMENT '申买价二',
    BidVolume2 INT NOT NULL DEFAULT 0 COMMENT '申买量二',
    AskPrice2 DOUBLE NOT NULL DEFAULT 0.0 COMMENT '申卖价二',
    AskVolume2 INT NOT NULL DEFAULT 0 COMMENT '申卖量二',
    BidPrice3 DOUBLE NOT NULL DEFAULT 0.0 COMMENT '申买价三',
    BidVolume3 INT NOT NULL DEFAULT 0 COMMENT '申买量三',
    AskPrice3 DOUBLE NOT NULL DEFAULT 0.0 COMMENT '申卖价三',
    AskVolume3 INT NOT NULL DEFAULT 0 COMMENT '申卖量三',
    BidPrice4 DOUBLE NOT NULL DEFAULT 0.0 COMMENT '申买价四',
    BidVolume4 INT NOT NULL DEFAULT 0 COMMENT '申买量四',
    AskPrice4 DOUBLE NOT NULL DEFAULT 0.0 COMMENT '申卖价四',
    AskVolume4 INT NOT NULL DEFAULT 0 COMMENT '申卖量四',
    BidPrice5 DOUBLE NOT NULL DEFAULT 0.0 COMMENT '申买价五',
    BidVolume5 INT NOT NULL DEFAULT 0 COMMENT '申买量五',
    AskPrice5 DOUBLE NOT NULL DEFAULT 0.0 COMMENT '申卖价五',
    AskVolume5 INT NOT NULL DEFAULT 0 COMMENT '申卖量五',
    AveragePrice DOUBLE NOT NULL DEFAULT 0.0 COMMENT '当日均价',
    ActionDay VARCHAR(9) NOT NULL COMMENT '业务日期',
    LocalTimestamp VARCHAR(30) NOT NULL DEFAULT '' COMMENT '本地时间戳',
    Timestamp BIGINT NOT NULL DEFAULT 0 COMMENT '消息时间戳(毫秒)',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    
    -- 索引
    UNIQUE KEY uk_instrument_trading_day_time (InstrumentID, TradingDay, UpdateTime, UpdateMillisec),
    INDEX idx_instrument_id (InstrumentID),
    INDEX idx_exchange_id (ExchangeID),
    INDEX idx_trading_day (TradingDay),
    INDEX idx_update_time (UpdateTime),
    INDEX idx_last_price (LastPrice),
    INDEX idx_volume (Volume),
    INDEX idx_created_at (created_at),
    INDEX idx_timestamp (Timestamp)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='市场行情数据表';

-- 插入示例数据（可选）
-- INSERT INTO market_data (
--     TradingDay, InstrumentID, ExchangeID, ExchangeInstID, LastPrice, PreSettlementPrice,
--     PreClosePrice, PreOpenInterest, OpenPrice, HighestPrice, LowestPrice, Volume,
--     Turnover, OpenInterest, ClosePrice, SettlementPrice, UpperLimitPrice, LowerLimitPrice,
--     PreDelta, CurrDelta, UpdateTime, UpdateMillisec, BidPrice1, BidVolume1, AskPrice1,
--     AskVolume1, BidPrice2, BidVolume2, AskPrice2, AskVolume2, BidPrice3, BidVolume3,
--     AskPrice3, AskVolume3, BidPrice4, BidVolume4, AskPrice4, AskVolume4, BidPrice5,
--     BidVolume5, AskPrice5, AskVolume5, AveragePrice, ActionDay, LocalTimestamp, Timestamp
-- ) VALUES (
--     '20250806', 'CU2508', 'SHFE', 'cu2508', 75500.0, 75200.0, 75100.0, 45230.0,
--     75300.0, 75800.0, 75000.0, 12568, 948750000.0, 45890.0, 75450.0, 75400.0,
--     82600.0, 68200.0, 0.0, 0.0, '14:30:15', 500, 75450.0, 10, 75500.0, 15,
--     75400.0, 8, 75550.0, 12, 75350.0, 5, 75600.0, 8, 75300.0, 3, 75650.0, 6,
--     75250.0, 4, 75700.0, 5, 75420.0, '20250806', '2025-08-06 14:30:15.500', 1722936615500
-- ); 