-- 创建资金账户表
CREATE TABLE IF NOT EXISTS trading_account (
    id BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '主键ID',
    BrokerID CHAR(11) NOT NULL COMMENT '经纪公司代码',
    AccountID CHAR(13) NOT NULL COMMENT '投资者帐号',
    PreMortgage DOUBLE NOT NULL DEFAULT 0.0 COMMENT '上次质押金额',
    PreCredit DOUBLE NOT NULL DEFAULT 0.0 COMMENT '上次信用额度',
    PreDeposit DOUBLE NOT NULL DEFAULT 0.0 COMMENT '上次存款额',
    PreBalance DOUBLE NOT NULL DEFAULT 0.0 COMMENT '上次结算准备金',
    PreMargin DOUBLE NOT NULL DEFAULT 0.0 COMMENT '上次占用的保证金',
    InterestBase DOUBLE NOT NULL DEFAULT 0.0 COMMENT '利息基数',
    Interest DOUBLE NOT NULL DEFAULT 0.0 COMMENT '利息收入',
    Deposit DOUBLE NOT NULL DEFAULT 0.0 COMMENT '入金金额',
    Withdraw DOUBLE NOT NULL DEFAULT 0.0 COMMENT '出金金额',
    FrozenMargin DOUBLE NOT NULL DEFAULT 0.0 COMMENT '冻结的保证金',
    FrozenCash DOUBLE NOT NULL DEFAULT 0.0 COMMENT '冻结的资金',
    FrozenCommission DOUBLE NOT NULL DEFAULT 0.0 COMMENT '冻结的手续费',
    CurrMargin DOUBLE NOT NULL DEFAULT 0.0 COMMENT '当前保证金总额',
    CashIn DOUBLE NOT NULL DEFAULT 0.0 COMMENT '资金差额',
    Commission DOUBLE NOT NULL DEFAULT 0.0 COMMENT '手续费',
    CloseProfit DOUBLE NOT NULL DEFAULT 0.0 COMMENT '平仓盈亏',
    PositionProfit DOUBLE NOT NULL DEFAULT 0.0 COMMENT '持仓盈亏',
    Balance DOUBLE NOT NULL DEFAULT 0.0 COMMENT '期货结算准备金',
    Available DOUBLE NOT NULL DEFAULT 0.0 COMMENT '可用资金',
    WithdrawQuota DOUBLE NOT NULL DEFAULT 0.0 COMMENT '可取资金',
    Reserve DOUBLE NOT NULL DEFAULT 0.0 COMMENT '基本准备金',
    TradingDay CHAR(9) NOT NULL COMMENT '交易日',
    SettlementID INT NOT NULL DEFAULT 0 COMMENT '结算编号',
    Credit DOUBLE NOT NULL DEFAULT 0.0 COMMENT '信用额度',
    Mortgage DOUBLE NOT NULL DEFAULT 0.0 COMMENT '质押金额',
    ExchangeMargin DOUBLE NOT NULL DEFAULT 0.0 COMMENT '交易所保证金',
    DeliveryMargin DOUBLE NOT NULL DEFAULT 0.0 COMMENT '投资者交割保证金',
    ExchangeDeliveryMargin DOUBLE NOT NULL DEFAULT 0.0 COMMENT '交易所交割保证金',
    ReserveBalance DOUBLE NOT NULL DEFAULT 0.0 COMMENT '保底期货结算准备金',
    CurrencyID CHAR(4) NOT NULL DEFAULT 'CNY' COMMENT '币种代码',
    PreFundMortgageIn DOUBLE NOT NULL DEFAULT 0.0 COMMENT '上次货币质入金额',
    PreFundMortgageOut DOUBLE NOT NULL DEFAULT 0.0 COMMENT '上次货币质出金额',
    FundMortgageIn DOUBLE NOT NULL DEFAULT 0.0 COMMENT '货币质入金额',
    FundMortgageOut DOUBLE NOT NULL DEFAULT 0.0 COMMENT '货币质出金额',
    FundMortgageAvailable DOUBLE NOT NULL DEFAULT 0.0 COMMENT '货币质押余额',
    MortgageableFund DOUBLE NOT NULL DEFAULT 0.0 COMMENT '可质押货币金额',
    SpecProductMargin DOUBLE NOT NULL DEFAULT 0.0 COMMENT '特殊产品占用保证金',
    SpecProductFrozenMargin DOUBLE NOT NULL DEFAULT 0.0 COMMENT '特殊产品冻结保证金',
    SpecProductCommission DOUBLE NOT NULL DEFAULT 0.0 COMMENT '特殊产品手续费',
    SpecProductFrozenCommission DOUBLE NOT NULL DEFAULT 0.0 COMMENT '特殊产品冻结手续费',
    SpecProductPositionProfit DOUBLE NOT NULL DEFAULT 0.0 COMMENT '特殊产品持仓盈亏',
    SpecProductCloseProfit DOUBLE NOT NULL DEFAULT 0.0 COMMENT '特殊产品平仓盈亏',
    SpecProductPositionProfitByAlg DOUBLE NOT NULL DEFAULT 0.0 COMMENT '根据持仓盈亏算法计算的特殊产品持仓盈亏',
    SpecProductExchangeMargin DOUBLE NOT NULL DEFAULT 0.0 COMMENT '特殊产品交易所保证金',
    BizType CHAR(1) NOT NULL DEFAULT '1' COMMENT '业务类型',
    FrozenSwap DOUBLE NOT NULL DEFAULT 0.0 COMMENT '延时换汇冻结金额',
    RemainSwap DOUBLE NOT NULL DEFAULT 0.0 COMMENT '剩余换汇额度',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    
    -- 索引
    UNIQUE KEY uk_broker_account_trading_day (BrokerID, AccountID, TradingDay),
    INDEX idx_broker_id (BrokerID),
    INDEX idx_account_id (AccountID),
    INDEX idx_trading_day (TradingDay),
    INDEX idx_balance (Balance),
    INDEX idx_available (Available),
    INDEX idx_position_profit (PositionProfit),
    INDEX idx_close_profit (CloseProfit),
    INDEX idx_created_at (created_at),
    INDEX idx_updated_at (updated_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='资金账户表';

-- 插入示例数据（可选）
-- INSERT INTO trading_account (
--     BrokerID, AccountID, PreMortgage, PreCredit, PreDeposit, PreBalance, PreMargin,
--     InterestBase, Interest, Deposit, Withdraw, FrozenMargin, FrozenCash, FrozenCommission,
--     CurrMargin, CashIn, Commission, CloseProfit, PositionProfit, Balance, Available,
--     WithdrawQuota, Reserve, TradingDay, SettlementID, Credit, Mortgage, ExchangeMargin,
--     DeliveryMargin, ExchangeDeliveryMargin, ReserveBalance, CurrencyID, PreFundMortgageIn,
--     PreFundMortgageOut, FundMortgageIn, FundMortgageOut, FundMortgageAvailable,
--     MortgageableFund, SpecProductMargin, SpecProductFrozenMargin, SpecProductCommission,
--     SpecProductFrozenCommission, SpecProductPositionProfit, SpecProductCloseProfit,
--     SpecProductPositionProfitByAlg, SpecProductExchangeMargin, BizType, FrozenSwap, RemainSwap
-- ) VALUES (
--     '9999', '123456789', 0.0, 0.0, 100000.0, 98500.0, 15000.0, 0.0, 0.0, 100000.0,
--     0.0, 0.0, 0.0, 0.0, 15000.0, 0.0, 120.0, 0.0, -1500.0, 98500.0, 83500.0,
--     83500.0, 0.0, '20250806', 1, 0.0, 0.0, 15000.0, 0.0, 0.0, 98500.0, 'CNY',
--     0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
--     '1', 0.0, 0.0
-- ); 